<a href="https://colab.research.google.com/github/lipakshipanda/Spectrum-Internship-Drive-2023/blob/main/Copy_of_Task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>**SPECTRUM INTENSHIP DRIVE 2023.**</center>


## <center>**The DS/ML internship of SID 2023.**</center>





<center>

# **TASK-1**





##### Run the below cell to download the csvs and files into your colab/jupyter notebook and start working with it. You will be needing all these for completing the task.

In [1]:
!wget https://raw.githubusercontent.com/Spectrum-CETB/Data-Science-AI/main/Datasets/creditcard.csv
!wget https://raw.githubusercontent.com/Spectrum-CETB/Data-Science-AI/main/Datasets/bmi.csv
!wget https://raw.githubusercontent.com/Spectrum-CETB/Data-Science-AI/main/Datasets/data.txt

--2023-12-09 06:27:44--  https://raw.githubusercontent.com/Spectrum-CETB/Data-Science-AI/main/Datasets/creditcard.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13782835 (13M) [text/plain]
Saving to: ‘creditcard.csv’

creditcard.csv      100%[===================>]  13.14M  --.-KB/s    in 0.06s   

2023-12-09 06:27:45 (223 MB/s) - ‘creditcard.csv’ saved [13782835/13782835]

--2023-12-09 06:27:45--  https://raw.githubusercontent.com/Spectrum-CETB/Data-Science-AI/main/Datasets/bmi.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Leng

#### WE WILL BE COVERING 3 MOST IMPORTANT CONCEPTS OF ML IN THIS WEEK.
#### 1)PYTHON
#### 2)NUMPY
#### 3)PANDAS

1) Write python code to calculate Mean, Median, Mode, Variance and Standard Deviation of the numbers in the below list without using any libraries.

In [2]:
numbers = [488, 296, 374, 189, 326, 229,  14, 162, 917, 778, 908, 376, 567,
162, 923, 130, 263, 655, 577, 486, 961, 966, 792,  19, 941, 722,
286, 191, 138, 704, 481, 230, 437, 592, 244, 885,   7, 524, 514,
483,  89, 779, 279, 478, 185, 940, 385,  43, 163, 571, 867, 492,
269,  23, 796, 888, 898, 725, 337, 573, 375, 916,  90, 743, 117,
742, 944, 358, 547, 975, 499, 469, 721, 665, 639,  70, 612, 338,
733, 634, 358, 524, 598, 466, 696, 691, 511, 450, 699,  76, 216,
359, 859, 754, 210, 309, 745,  38, 934, 541]


# calculating mean, median, mode, variance & standard variance of the given list of numbers
mean = sum(numbers) / len(numbers)

fig = sorted(numbers)
if len(numbers) % 2 == 0:
    mid1 = len(numbers) // 2
    mid2 = mid1 - 1
    median = (fig[mid1] + fig[mid2]) / 2
else:
    albus = len(numbers) // 2
    median = fig[albus]

ron = {}
for secert in numbers:
    ron[secert] = ron.get(secert, 0) + 1
mode = [k for k, v in ron.items() if v == max(ron.values())]

sqdiff= [(x - mean) ** 2 for x in numbers]
variance = sum(sqdiff) / len(numbers)

import math
std_deviation = math.sqrt(variance)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Mode: {mode}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_deviation}")

Mean: 499.38
Median: 495.5
Mode: [162, 524, 358]
Variance: 78991.79559999998
Standard Deviation: 281.05479109952915


2) Use the lambda and map() to square the numbers in the numbers list and store them in a newly created list known as squared. Then use filter() to create a  new list of all even numbers from the squared list.

In [3]:
squared = list(map(lambda x: x ** 2, numbers))
even_squared = list(filter(lambda x: x % 2 == 0, squared))
print("Squared numbers:", squared)
print("Even squared numbers:", even_squared)

Squared numbers: [238144, 87616, 139876, 35721, 106276, 52441, 196, 26244, 840889, 605284, 824464, 141376, 321489, 26244, 851929, 16900, 69169, 429025, 332929, 236196, 923521, 933156, 627264, 361, 885481, 521284, 81796, 36481, 19044, 495616, 231361, 52900, 190969, 350464, 59536, 783225, 49, 274576, 264196, 233289, 7921, 606841, 77841, 228484, 34225, 883600, 148225, 1849, 26569, 326041, 751689, 242064, 72361, 529, 633616, 788544, 806404, 525625, 113569, 328329, 140625, 839056, 8100, 552049, 13689, 550564, 891136, 128164, 299209, 950625, 249001, 219961, 519841, 442225, 408321, 4900, 374544, 114244, 537289, 401956, 128164, 274576, 357604, 217156, 484416, 477481, 261121, 202500, 488601, 5776, 46656, 128881, 737881, 568516, 44100, 95481, 555025, 1444, 872356, 292681]
Even squared numbers: [238144, 87616, 139876, 106276, 196, 26244, 605284, 824464, 141376, 26244, 16900, 236196, 933156, 627264, 521284, 81796, 19044, 495616, 52900, 350464, 59536, 274576, 264196, 228484, 883600, 242064, 633616,

3)Sort the below dictionary in descending order of the age of employees.

In [4]:
'''
Key - Name
Value - [Vaccination Status,Age]
'''
data = {'Ben':['Vaccinated',35],'Luke':['Not Vaccinated',28],'Anakin':['Vaccinated',55],'Leia':['Vaccinated',28],'Han':['Not Vaccinated',60]}

saga = dict(sorted(data.items(), key=lambda item: item[1][1], reverse=True))
for naam, daak in saga.items():
    print(f'{naam}: {daak[1]} years old ({daak[0]})')

Han: 60 years old (Not Vaccinated)
Anakin: 55 years old (Vaccinated)
Ben: 35 years old (Vaccinated)
Luke: 28 years old (Not Vaccinated)
Leia: 28 years old (Vaccinated)


4)Using file handling, extract and read data from the data.txt file and find the most common occuring 5 words.

In [5]:
# refering to the data.text for 5 common words
with open('data.txt', 'r') as akshi:
    yaho = akshi.read()
    import string
    translator = str.maketrans('', '', string.punctuation)
    yaho= yaho.translate(translator).lower()

hike = yaho.split()
from collections import Counter
mall = Counter(hike)
deal =mall.most_common(5)

for hike, count in deal:
    print(f'{hike}: {count}')

learning: 14
machine: 10
of: 8
to: 6
is: 5


### 2)Numpy

In [6]:
# run this cell and then proceed further
import numpy as np

* You will be given few matrices and you have to write a few lines of code which will be resulting the following outputs.

In [7]:
mat = np.arange(0,25).reshape(5,5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

1)The given array is above i.e (mat).
- You have to write a code such that the output looks like-
      array([[ 5,  6,  7,  8,  9],
             [10, 11, 12, 13, 14],
             [15, 16, 17, 18, 19]])

In [8]:
import numpy as np
mat=np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
dobby=mat[1:4,:]
print(dobby)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


2)Convert the array 'x' into a 3x4 matrix

In [9]:
x= np.arange(0,12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
import numpy as np
x = np.arange(0,12)
luna=x.reshape(3,4)
print(luna)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


3) Find the inverse and transpose of the 3x4 matrix obtained above.

In [11]:
import numpy as np

jiji=np.array([[0,1,2,3],
               [4,5,6,7],
               [8,9,10,11]])
newt=np.zeros((4,4))
newt[:3,:4]=jiji
dert=np.linalg.det(newt)

if dert==0:
  print('inverse of matrix does not exist')
else:
  print('determinant is:',dert)

transpose_matrix=jiji.T

print('transpose matrix is:')
print(transpose_matrix)

inverse of matrix does not exist
transpose matrix is:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


4) Write a code to find the position of all zeros present in the matrix 'y

In [12]:
y=np.array(([0,5,9,0],[0,0,4,7],[9,3,0,6]))
y

array([[0, 5, 9, 0],
       [0, 0, 4, 7],
       [9, 3, 0, 6]])

In [13]:
import numpy as np
def find_zeros_positions(black):
    hagrid = np.argwhere(black == 0)
    return hagrid

sirius = find_zeros_positions(y)

print("Positions of zeros in the matrix:")
for position in sirius:
    print(tuple(position))

Positions of zeros in the matrix:
(0, 0)
(0, 3)
(1, 0)
(1, 1)
(2, 2)


### 3)Pandas

In [14]:
# run this cell and then proceed further
import pandas as pd

#### Read the data from the csv named "bmi.csv" and complete the task that follows.
1)Your first task is to create a new column in the dataframe named "BMI" index, which reads data from the "Weight" and "Height" Column, and calculates the BMI based on this. Display the top 10 rows of this dataframe after adding the new column.


In [15]:
import pandas as pd
snap = pd.read_csv("bmi.csv")
snap['BMI']=snap['weight(in kg)']/(snap['height(in m)']**2)
print(snap.head(10))

  animal  age  weight(in kg)  height(in m)        BMI
0    cat    3             14           1.3   8.284024
1    dog    9             11           1.2   7.638889
2    dog    1              5           1.2   3.472222
3    cat   10              9           0.9  11.111111
4    cat    8              5           1.2   3.472222
5    cat    2             11           1.1   9.090909
6    dog   10             14           1.0  14.000000
7    dog    8              9           1.0   9.000000
8    cat   10             12           0.8  18.750000
9    cat    6              9           0.7  18.367347


2)From the dataframe, find out the count, mean ,standard deviation ,datatype, and number of non-null objects of each column.

In [16]:
import pandas as pd

snap = pd.read_csv("bmi.csv")
snap['BMI'] = snap['weight(in kg)'] / (snap['height(in m)'] ** 2)
status = snap.describe()
peter = snap.info()
print("count, mean & standard deviation is:")
print(status)
print("data types and non-null counts for all columns:\n")
print(peter)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   animal         20 non-null     object 
 1   age            20 non-null     int64  
 2   weight(in kg)  20 non-null     int64  
 3   height(in m)   20 non-null     float64
 4   BMI            20 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 928.0+ bytes
count, mean & standard deviation is:
             age  weight(in kg)  height(in m)        BMI
count  20.000000      20.000000     20.000000  20.000000
mean    6.600000       9.050000      0.985000  10.586173
std     2.962929       2.981963      0.213431   5.250493
min     1.000000       5.000000      0.700000   3.472222
25%     4.500000       6.750000      0.800000   6.129630
50%     7.500000       9.000000      1.000000  10.101010
75%     9.000000      11.250000      1.200000  14.071429
max    10.000000      14.00000

3)In the column "animal" find the number ,of unique values and the count of each of the unique values.

In [17]:
import pandas as pd

snap= pd.read_csv("bmi.csv")
snap['BMI'] = snap['weight(in kg)'] / (snap['height(in m)'] ** 2)

tonks = snap['animal'].nunique()
value_counts =snap['animal'].value_counts()

print("number of unique values in 'animal' column:", tonks)
print("Count of Each Unique Value in 'animal' column:\n")
print(value_counts)

number of unique values in 'animal' column: 2
Count of Each Unique Value in 'animal' column:

cat    13
dog     7
Name: animal, dtype: int64


4)Scale the data of columns "weight" and "height" in such a way that all the values lie between 0 and 1.

In [18]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

snap = pd.read_csv("bmi.csv")

potter = MinMaxScaler()
snap[['weight(in kg)', 'height(in m)']] = potter.fit_transform(snap[['weight(in kg)', 'height(in m)']])

print(snap.head(10))

  animal  age  weight(in kg)  height(in m)
0    cat    3       1.000000      1.000000
1    dog    9       0.666667      0.833333
2    dog    1       0.000000      0.833333
3    cat   10       0.444444      0.333333
4    cat    8       0.000000      0.833333
5    cat    2       0.666667      0.666667
6    dog   10       1.000000      0.500000
7    dog    8       0.444444      0.500000
8    cat   10       0.777778      0.166667
9    cat    6       0.444444      0.000000


5)Calculate the mean "height", "weight" and "age" of each different animal.
Hint: groupby()

In [19]:
import pandas as pd
snap = pd.read_csv("bmi.csv")

means = snap.groupby('animal').mean()[['height(in m)', 'weight(in kg)', 'age']]
means = means.rename(columns={'height(in m)': 'mean height', 'weight(in kg)': 'mean weight', 'age': 'mean age'})

print(means)

        mean height  mean weight  mean age
animal                                    
cat        0.938462     8.923077  6.769231
dog        1.071429     9.285714  6.285714


#### Read the data from the csv named "creditcard.csv". And perform the following tasks.

6)Find the number of males in the age range of 30 to 60 (including both 30 and 60 here), who have the occupation of "Self_Employed"

In [20]:
import pandas as pd

mool = pd.read_csv("creditcard.csv")
specify = mool[(mool['Age'] >= 30) & (mool['Age'] <= 60) & (mool['Occupation'] == 'Self_Employed') & (mool['Gender'] == 'Male')]
evan = len(specify)

print("Number of males in the age range of 30 to 60 those are 'Self_Employed':", evan)

Number of males in the age range of 30 to 60 those are 'Self_Employed': 56231


7)Find the number of males and females who were active in the last 3 months (if the Is_Active column shows "Yes", that means that customer was active in the last 3 months, else he/she wasn't).

In [21]:
import pandas as pd
mool = pd.read_csv("creditcard.csv")
active = mool[mool['Is_Active'] == 'Yes']
mem_count = active['Gender'].value_counts()
print("number of males active in the last 3 months:", mem_count.get("Male", 0))
print("number of females active in the last 3 months:", mem_count.get("Female", 0))

number of males active in the last 3 months: 55948
number of females active in the last 3 months: 39487


8)Find the percentage of null values in the column "Credit_Product", and replace them all with the value which is lesser among "yes" or "no" in the column.

In [22]:
import pandas as pd

mool = pd.read_csv("creditcard.csv")
null_percent = (mool['Credit_Product'].isnull().sum() / len(mool)) * 100
argus = mool['Credit_Product'].eq('yes').sum()
count_no = mool['Credit_Product'].eq('no').sum()
replace_value = 'yes' if argus <= count_no else 'no'
mool['Credit_Product'].fillna(replace_value, inplace=True)
print("Percentage of null values in 'Credit_Product' column:", null_percent, "%")
print("Replacing null values with:", replace_value)

Percentage of null values in 'Credit_Product' column: 11.9340726421813 %
Replacing null values with: yes


# <center>CONGRATULATIONS!! YOU FINALLY COMPLETED THE TASK-1.WE WILL BE COMING WITH EVEN MORE INTERESTING CONCEPTS IN THE NEXT TASK.
#    <center>TILL THEN **HAPPY MACHINE LEARNING!!.**</center>